name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Check format
      run: cargo fmt -- --check
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- --deny warnings
    - name: Check fallback implementation
      run: cargo check --features __test_unsupported
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test
